modLoader="javafml"
loaderVersion="[47,)" # Match your Forge version
license="MIT"

[[mods]]
modId="mcemu"
version="1.0.0"
displayName="MCEmu"
authors="Your Name"
description='''NES Emulator for Minecraft'''

[[dependencies.mcemu]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"